name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Composer dependencies if any
        uses: php-actions/composer@v6 # or alternative dependency management
      - name: Run PHPStan
        uses: php-actions/phpstan@v3
        with:
          generate_baseline: baseline.db
          path: src/
